---
- hosts: idoit
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## create directories
  #################################
  - name: create directory idoit
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/idoit"
      state: directory

  - name: create directory upload files
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/upload/files"
      state: directory

  - name: create directory upload images
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/upload/images"
      state: directory

  ##################################
  ## install idoit
  ##################################

  - name: download and install zip file
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      src: https://sourceforge.net/projects/i-doit/files/i-doit/{{idoit_release}}/idoit-open-{{idoit_release}}.zip/download
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/idoit

  - name: upload installation patch
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/installation_hs_db.patch" src="templates/installation_hs_db.patch" mode=0600

  - name: patch the installation script to work without database root permissions
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      patch -p1 < /home/pacs/{{pac}}/users/{{user}}//installation_hs_db.patch || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_installation_patched
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/idoit"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_installation_patched"

  ##################################
  ## configuration
  ##################################

  # TODO: src/config.inc.php

  ######################
  ## initialise instance
  ######################

  # TODO

  ########################
  ## setup the apache site
  ########################
  - name: Check for htdocs-ssl directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    stat:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
    register: htdocsssl
  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent
    when: htdocsssl.stat.exists and htdocsssl.stat.isdir
  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/idoit"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link
  - name: upload .htaccess file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template:
      src: "templates/htaccess"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/.htaccess"
  - name: upload php.ini file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template:
      src: "templates/php.ini"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/fastcgi-ssl/php.ini"
